const actionTypes = {
    NEW_MOVE : 'NEW_MOVE',
    NEW_GAME : 'NEW_GAME',
    GENERATE_ALLOWED_MOVES : 'GENERATE_ALLOWED_MOVES',
    CLEAR_ALLOWED_MOVES : 'CLEAR_ALLOWED_MOVES',
    PROMOTION_OPEN : 'PROMOTION_OPEN',
    PROMOTION_CLOSE : 'PROMOTION_CLOSE',
    CAN_CASTLE : 'CAN_CASTLE',
    STALEMATE : 'STALEMATE',
}

export default actionTypes